### ISSUE TITLE
[QUESTION] - Focus/change focus of inner component in container

### ISSUE THREAD

**Issue by AdaShoelace** [veeso/tui-realm-stdlib#16]
How are you supposed to toggle focus between inner components in a container?
The only way I've managed to come up with is overriding `focus` which is discouraged in the documentation.

**Comment by veeso** [comment]
In case of containers is ok, because they are not component with an ID, so you cannot call `active` on `App` for the inner components, but only for the outer Container.

**Comment by AdaShoelace** [comment]
Thanks!

I ended up implementing my own component based on the container code. I realized I tried to make container act as something it is not.
