### ISSUE TITLE
[BUG] - Table component focus handling

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm-stdlib#3]
## Description

I'm using table with scrollable option enabled. When I update the table, the focus will lose. I have to do self.view.active to focus it again.

## Steps to reproduce
I found below code in update function of table.rs:
```
if self.scrollable() {
            self.blur();
}
```

## Expected behavior
I comment out above code, and the focus seems no problem any more. I'm not sure if there is any side effect?

## Environment

- OS:  GNU/Linux]
- Architecture  x86_64
- Rust version: 1.54
- tui-realm version: 0.6.1

**Comment by veeso** [comment]
Yep, there should be a not `!` in front of the statement. I'm gonna fix asap.

**Comment by veeso** [comment]
Fixed in 0.6.2
