### ISSUE TITLE
[BUG] - Textarea length calculation is wrong when enable scroll

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm-stdlib#4]
## Description

I used textarea in a new app. The last word on each line is missing when I enable scroll.

## Steps to reproduce

```
                    .with_highlighted_str(Some("\u{1f680}"))
                    .with_max_scroll_step(4)
```

## Expected behaviour

I think the wrap_span in render fn of textarea could be modified to fix it. But I'm not sure how to calculate the width of highlight str.

## Environment

- OS: arch
- Architecture   x86_64
- Rust version v1.56
- tui-realm version v0.6.0

**Comment by veeso** [comment]
Should be fixed in 0.6.4
