### ISSUE TITLE
Status check

### ISSUE THREAD

**Issue by lkadalski** [veeso/tui-realm-stdlib#5]
Hi @veeso, I'm glad that you found time to develop such library. The idea behind it is very cool. :+1:
I would like to utilize your library to my new application but I see that you are doing heavy refactor right now. 
TBH I don't see many mature _frameworks_ for TUI applications. Maybe you are close to 1.0, may I help you somehow ?

**Comment by veeso** [comment]
Hi there!

I'm going to release the 1.0.0 version of the framework on sunday, I'm just finishing writing examples and recording a crash course, so it's basically finished.

If you want to start using it, you can in the meantime include the library in your project using the git url with branch `new-api` for `tuirealm` and `1.0.0` for the standard library. In the `new-api` branch you will also be able to find all the documentation for the library.

**Comment by veeso** [comment]
tui-realm 1.0.0 is OUT! 🎉

**Comment by lkadalski** [comment]
Yay, will check it out
