### ISSUE TITLE
[Feature Request] - Text wrapping in input

### ISSUE THREAD

**Issue by LukasDoesDev** [veeso/tui-realm-stdlib#7]
## Description

Text wrapping is necessary when writing large lines of text.

### Changes

The following changes to the application are expected

- Text wrapping boolean property on `Input` mock components
- Cursor up/down command

**Comment by LukasDoesDev** [comment]
Would be great in Paragraphs and Spans too

**Comment by veeso** [comment]
This would require a new component. I can put this on my todo list.

**Comment by veeso** [comment]
This component has been implemented as a standalone library <https://github.com/veeso/tui-realm-textarea>
